export const cards = [
    {
      id: 1,
      title: "Lập trình",
      desc: "Website, API, source code",
      cat: "web",
      link: "/gigs?cat=web",
      icon: "💻",
      img: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 2,
      title: "Thiết kế",
      desc: "Logo, poster, PowerPoint",
      cat: "design",
      link: "/gigs?cat=design",
      icon: "🎨",
      img: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 3,
      title: "Content",
      desc: "Bài viết, SEO, mô tả sản phẩm",
      cat: "writing",
      link: "/gigs?cat=writing",
      icon: "✍️",
      img: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 4,
      title: "Media",
      desc: "Video, thumbnail, chỉnh ảnh",
      cat: "video",
      link: "/gigs?cat=video",
      icon: "🎬",
      img: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 5,
      title: "Học tập",
      desc: "Tài liệu, ebook, template báo cáo",
      cat: "education",
      link: "/gigs?cat=education",
      icon: "📚",
      img: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 6,
      title: "Sản phẩm số",
      desc: "Template, UI kit, source mẫu",
      link: "/gigs?type=digital_product",
      icon: "📦",
      img: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 7,
      title: "Dịch vụ kỹ năng",
      desc: "Thuê talent làm theo yêu cầu",
      link: "/gigs?type=skill_service",
      icon: "🤝",
      img: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 8,
      title: "Template",
      desc: "CV, báo cáo, landing page",
      link: "/gigs?search=template",
      icon: "🧩",
      img: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80",
    },
  ];
  
  export const projects = [
    { id: 1, img: "/img/demo.png", pp: "/img/noavatar.png", cat: "React E-commerce Template", username: "code_talent" },
    { id: 2, img: "/img/demo.png", pp: "/img/noavatar.png", cat: "Thiết kế PowerPoint thuyết trình", username: "design_talent" },
    { id: 3, img: "/img/demo.png", pp: "/img/noavatar.png", cat: "Template báo cáo tiểu luận Word", username: "study_talent" },
    { id: 4, img: "/img/demo.png", pp: "/img/noavatar.png", cat: "Edit video TikTok/Reels", username: "media_talent" },
    { id: 5, img: "/img/demo.png", pp: "/img/noavatar.png", cat: "Viết mô tả sản phẩm chuẩn SEO", username: "content_talent" },
    { id: 6, img: "/img/demo.png", pp: "/img/noavatar.png", cat: "UI Kit landing page SaaS", username: "design_talent" },
  ];
  
  export const gigs = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai art character from your images and prompts",
      price: 59,
      star: 5,
      username: "Anna Bell",
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ultra high quality character art with ai",
      price: 79,
      star: 5,
      username: "Lannie Coleman",
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will creating unique ai generated artworks mid journey ai artist",
      price: 112,
      star: 5,
      username: "Carol Steve",
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom ai generated artwork using your photos",
      price: 99,
      star: 4,
      username: "Don Weber",
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will recreate your dreams in high quality pictures",
      price: 59,
      star: 5,
      username: "Audrey Richards",
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai digital art illustration hyper realistic painting",
      price: 79,
      star: 4,
      username: "Walton Shepard ",
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will generate images with your prompts using ai dalle",
      price: 89,
      star: 5,
      username: "Waverly Schaefer",
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom art using midjourney generator",
      price: 110,
      star: 4,
      username: "Wilton Hunt",
    },
  ];
